Do push changes back from syncgover

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -50,9 +50,7 @@ jobs:
           SQS_QUEUE_URL: https://sqs.ap-northeast-1.amazonaws.com/123456789012/myqueue
       - name: Push code changes back to the repository
         run: |
-          if ! git diff --exit-code; then
-            git push || echo "Unable to push changes"
-          fi
+          git push || echo "Unable to push changes"
   goreleaser:
     runs-on: ubuntu-latest
     steps:
