Fix syncgover git push back

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -49,8 +49,10 @@ jobs:
           # This one is for setupSQSQueue in main_test
           SQS_QUEUE_URL: https://sqs.ap-northeast-1.amazonaws.com/123456789012/myqueue
       - name: Push code changes back to the repository
+        if: github.event_name == 'pull_request'
         run: |
-          git push || echo "Unable to push changes"
+          echo Pushing changes to ${GITHUB_HEAD_REF}
+          git push origin HEAD:${GITHUB_HEAD_REF} || echo "Unable to push changes"
   goreleaser:
     runs-on: ubuntu-latest
     steps:
