Fail gracefully on git-push error for a while

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -47,5 +47,5 @@ jobs:
       - name: Push code changes back to the repository
         run: |
           if ! git diff --exit-code; then
-            git push
+            git push || echo "Unable to push changes"
           fi
